### ISSUE TITLE
아이템1 Collections 에 대한 말 무슨 말인지 모르겠다 

### ISSUE THREAD

**Issue by sYrongK** [doremi-study/books.effective-java#2]
- 클래스를 공개하지 않는다는게 무슨 의미인지?  클래스를 공개하지 않음으로써 api를 작게 유지할 수 있다고 얘기하는 것 같은데 인스턴스 화처럼 객체를 직접적으로 다루는 부분이 말 그대로 내부로 들어가지 않는 이상 안 보인다는 의미인 건지? 
- 동반 클래스가 무슨 말일까 이너 클래스 말하는 걸까 ? 검색했더니 kotlin에 동반 객체 이런게 나왔음
- 정적 팩토리 클래스를 사용하면 얻어 온 객체를 해당 클래스가 아닌 인터페이스로 다루게 된다는 것도 무슨 의미인지?

무슨 말인지 대충 이해하고 넘어가고 싶은데 대충 이해가 안되어서 속도가 안 남 
일단 아이템1에서 이 부분 빠트리지 말고 정리해두기

**Comment by hankk20** [comment]
링크로 대신
[정적팩토리](https://www.notion.so/hankk/44eb3193ba45463b89a3ee7e464faf72)

그래도 이해 안되면 회의실로
